version: '3'
services:
  #PHP Service
  app:
    build:
      args:
        user: bow-valley
        uid: 1000
      context: .
      dockerfile: ./docker/php/Dockerfile
    image: php-laravel
    container_name: app-bow-valley
    restart: unless-stopped
    tty: true
    extra_hosts:
      - "host.docker.internal:127.0.0.1"
    environment:
      SERVICE_NAME: app-bow-valley
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
      - /tmp/xdebug:/tmp/xdebug
    networks:
      - bow-valley_network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver-bow-valley
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - bow-valley_network

  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: mysql-bow-valley
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: bow-valley
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_USER: db_user
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql-bow-valley
    volumes:
      - dbdata:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - bow-valley_network

  #Mailhog Service
  mailhog:
      image: 'mailhog/mailhog:latest'
      container_name: mailhog-bow-valley
      ports:
          - '8025:8025'
      networks:
        - bow-valley_network

  phpmyadmin:
      container_name: phpmyadmin-bow-valley
      image: phpmyadmin/phpmyadmin:latest
      restart: always
      environment:
        - PMA_ARBITRARY=1
        - PMA_HOST=mysql-bow-valley
      ports:
        - "9090:80"
      networks:
      - bow-valley_network

#React application
  react-app:
      image: node:alpine
      build: 
        context: .
        dockerfile: ./docker/react/Dockerfile
      container_name: milestone-react-app
      ports:
        - "8000:8000"
      restart: unless-stopped
      command: ["npm", "run", "dev"]
      working_dir: /app
      volumes:
        - ./react:/app
      tty: true
      
#Docker Networks
networks:
  bow-valley_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.57.0/24
#Volumes
volumes:
  dbdata:
    driver: local

